#!/bin/sh

case "$1" in
    start)
        echo "Loading ldd modules"
        modprobe hello

        modprobe faulty
        major=$(awk "\$2==\"faulty\" {print \$1}" /proc/devices)
        rm -f /dev/faulty
        mknod /dev/faulty c $major 0
        chmod 666 /dev/faulty

        modprobe scull
        major=$(awk "\$2==\"scull\" {print \$1}" /proc/devices)
        rm -f /dev/scull[0-3]
        mknod /dev/scull0 c $major 0
        mknod /dev/scull1 c $major 1
        mknod /dev/scull2 c $major 2
        mknod /dev/scull3 c $major 3
        chmod 666 /dev/scull[0-3]
        ;;
    stop)
        echo "Unloading ldd modules"
        rmmod scull
        rmmod faulty
        rmmod hello
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
